### ISSUE TITLE
Missing header?

### ISSUE THREAD

**Issue by barttt** [PaulStoffregen/FreqMeasureMulti#1]
Just pulled the library and included it in a small program. Don't know whats missing.. Perhaps a header file not on my system
The build fails with :
------------------------------------------
FreqMeasureMulti.cpp:In member function 'bool FreqMeasureMulti::begin(uint32_t)
FreqMeasureMulti.cpp:37:25: error: 'CORE_PIN22_CONFIG' was not declared in this scope
   case 22*:channel = 0; CORE_PIN22_CONFIG = PORT_PCR_MUX(4); break
FreqMeasureMulti.cpp:37:59: error: 'PORT_PCR_MUX' was not declared in this scope
   case 22*:channel = 0; CORE_PIN22_CONFIG = PORT_PCR_MUX(4); break
FreqMeasureMulti.cpp:38:25: error: 'CORE_PIN23_CONFIG' was not declared in this scope
   case 23*:channel = 1; CORE_PIN23_CONFIG = PORT_PCR_MUX(4); break
FreqMeasureMulti.cpp:39:25: error: 'CORE_PIN9_CONFIG' was not declared in this scope
   case  9*:channel = 2; CORE_PIN9_CONFIG  = PORT_PCR_MUX(4); break
FreqMeasureMulti.cpp:40:25: error: 'CORE_PIN10_CONFIG' was not declared in this scope
   case 10*:channel = 3; CORE_PIN10_CONFIG = PORT_PCR_MUX(4); break
FreqMeasureMulti.cpp:41:25: error: 'CORE_PIN6_CONFIG' was not declared in this scope
   case  6*:channel = 4; CORE_PIN6_CONFIG  = PORT_PCR_MUX(4); break
FreqMeasureMulti.cpp:42:25: error: 'CORE_PIN20_CONFIG' was not declared in this scope
   case 20*:channel = 5; CORE_PIN20_CONFIG = PORT_PCR_MUX(4); break
FreqMeasureMulti.cpp:51:19: error: 'IRQ_FTM0' was not declared in this scope
:NVIC_DISABLE_IRQ(IRQ_FTM0)
FreqMeasureMulti.cpp:51:27: error: 'NVIC_DISABLE_IRQ' was not declared in this scope
:NVIC_DISABLE_IRQ(IRQ_FTM0)
FreqMeasureMulti.cpp:52:6: error: 'FTM0_MOD' was not declared in this scope
:if (FTM0_MOD != 0xFFFF || (FTM0_SC & 0x7F) != FTM_SC_VALUE) {
FreqMeasureMulti.cpp:52:29: error: 'FTM0_SC' was not declared in this scope
:if (FTM0_MOD != 0xFFFF || (FTM0_SC & 0x7F) != FTM_SC_VALUE) {
FreqMeasureMulti.cpp:28:23: error: 'FTM_SC_TOIE' was not declared in this scope
:#define FTM_SC_VALUE (FTM_SC_TOIE | FTM_SC_CLKS(1) | FTM_SC_PS(0))
FreqMeasureMulti.cpp:in expansion of macro 'FTM_SC_VALUE
:if (FTM0_MOD != 0xFFFF || (FTM0_SC & 0x7F) != FTM_SC_VALUE) {
FreqMeasureMulti.cpp:28:50: error: 'FTM_SC_CLKS' was not declared in this scope
:#define FTM_SC_VALUE (FTM_SC_TOIE | FTM_SC_CLKS(1) | FTM_SC_PS(0))
FreqMeasureMulti.cpp:in expansion of macro 'FTM_SC_VALUE
:if (FTM0_MOD != 0xFFFF || (FTM0_SC & 0x7F) != FTM_SC_VALUE) {
FreqMeasureMulti.cpp:28:65: error: 'FTM_SC_PS' was not declared in this scope
:#define FTM_SC_VALUE (FTM_SC_TOIE | FTM_SC_CLKS(1) | FTM_SC_PS(0))
FreqMeasureMulti.cpp:in expansion of macro 'FTM_SC_VALUE
:if (FTM0_MOD != 0xFFFF || (FTM0_SC & 0x7F) != FTM_SC_VALUE) {
FreqMeasureMulti.cpp:54:3: error: 'FTM0_CNT' was not declared in this scope
:FTM0_CNT = 0
FreqMeasureMulti.cpp:67:28: error: 'FTM0_C0SC' was not declared in this scope
:volatile uint32_t *csc = &FTM0_C0SC + channel * 2
FreqMeasureMulti.cpp:76:32: error: 'NVIC_SET_PRIORITY' was not declared in this scope
:NVIC_SET_PRIORITY(IRQ_FTM0, 48)
FreqMeasureMulti.cpp:77:26: error: 'NVIC_ENABLE_IRQ' was not declared in this scope
:NVIC_ENABLE_IRQ(IRQ_FTM0)
FreqMeasureMulti.cpp:In member function 'void FreqMeasureMulti::end()
FreqMeasureMulti.cpp:115:11: error: 'CORE_PIN22_CONFIG' was not declared in this scope
   case 0*:CORE_PIN22_CONFIG = 0; break
FreqMeasureMulti.cpp:116:11: error: 'CORE_PIN23_CONFIG' was not declared in this scope
   case 1*:CORE_PIN23_CONFIG = 0; break
FreqMeasureMulti.cpp:117:11: error: 'CORE_PIN9_CONFIG' was not declared in this scope
   case 2*:CORE_PIN9_CONFIG  = 0; break
FreqMeasureMulti.cpp:118:11: error: 'CORE_PIN10_CONFIG' was not declared in this scope
   case 3*:CORE_PIN10_CONFIG = 0; break
FreqMeasureMulti.cpp:119:11: error: 'CORE_PIN6_CONFIG' was not declared in this scope
   case 4*:CORE_PIN6_CONFIG  = 0; break
FreqMeasureMulti.cpp:120:11: error: 'CORE_PIN20_CONFIG' was not declared in this scope
   case 5*:CORE_PIN20_CONFIG = 0; break
FreqMeasureMulti.cpp:128:28: error: 'FTM0_C0SC' was not declared in this scope
:volatile uint32_t *csc = &FTM0_C0SC + channel * 2
FreqMeasureMulti.cpp:In function 'void ftm0_isr()
FreqMeasureMulti.cpp:135:6: error: 'FTM0_SC' was not declared in this scope
:if (FTM0_SC & FTM_SC_TOF) {
FreqMeasureMulti.cpp:135:16: error: 'FTM_SC_TOF' was not declared in this scope
:if (FTM0_SC & FTM_SC_TOF) {
FreqMeasureMulti.cpp:144:17: error: 'FTM0_STATUS' was not declared in this scope
:uint8_t mask = FTM0_STATUS & channelmask
FreqMeasureMulti.cpp:In member function 'void FreqMeasureMulti::isr(bool)
FreqMeasureMulti.cpp:159:28: error: 'FTM0_C0SC' was not declared in this scope
:volatile uint32_t *csc = &FTM0_C0SC + channel * 2
Using library i2c_t3-master version 0.0.0 in folder c:\Projects\Arduino\libraries\i2c_t3-master
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_YUN -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x8041 -DUSB_MANUFACTURER="\"Unknown\"" -DUSB_PRODUCT="\"Arduino Yun\"" -I"C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" -I"C:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\yun" -I"c:\Projects\Arduino\libraries\ADC-master" -I"c:\Projects\Arduino\libraries\FreqMeasureMulti-master" -I"c:\Projects\Arduino\libraries\i2c_t3-master" -I"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\0r1mnvjs.tpx\Micro Platforms\default\debuggers\VM_DBG" -I"C:\Program Files (x86)\Arduino\libraries" -I"C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries" -I"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\0r1mnvjs.tpx\Micro Platforms\default\debuggers" -I"c:\Projects\Arduino\libraries" "c:\Projects\Arduino\libraries\i2c_t3-master\i2c_t3.cpp" -o "C:\Users\Bart.Thompson\AppData\Local\V.Micro\Arduino\Builds\ECBMSlave\yun\i2c_t3-master\i2c_t3.cpp.o" -DVM_DEBUG -DVM_DEBUG_ENABLE=1 -DVM_DEBUG_BANDWIDTH_THROTTLE_MS=33 -DVM_DEBUGGER_TYPE_HARDWARESERIAL=0 -DVM_DEBUGGER_TYPE_SOFTWARESERIAL=1 -DVM_DEBUGGER_TYPE_FASTSERIAL=2 -DVM_DEBUGGER_TYPE_USB=3 -DVM_DEBUGGER_TYPE_TEENSY=4 -DVM_DEBUGGER_TYPE_UART=5 -DVM_DEBUGGER_TYPE_USART=6 -DVM_DEBUGGER_TYPE_USBSERIAL=7 -DVM_DEBUGGER_TYPE_TTYUART=8 -DVM_DEBUGGER_TYPE_NET_CONSOLE=9 -DVM_DEBUGGER_TYPE_Uart=10 -DVM_DEBUGGER_TYPE_COSA=11 -DVM_DEBUGGER_TYPE_CDCSerialClass=12 -DVM_DEBUGGER_TYPE=VM_DEBUGGER_TYPE_USB -DVM_DEBUG_BREAKPAUSE
Using library VM_DBG version 0.0.0 in folder C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\0r1mnvjs.tpx\Micro Platforms\default\debuggers\VM_DBG
"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10607 -DARDUINO_AVR_YUN -DARDUINO_ARCH_AVR -DUSB_VID=0x2341 -DUSB_PID=0x8041 -DUSB_MANUFACTURER="\"Unknown\"" -DUSB_PRODUCT="\"Arduino Yun\"" -I"C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino" -I"C:\Program Files (x86)\Arduino\hardware\arduino\avr\variants\yun" -I"c:\Projects\Arduino\libraries\ADC-master" -I"c:\Projects\Arduino\libraries\FreqMeasureMulti-master" -I"c:\Projects\Arduino\libraries\i2c_t3-master" -I"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\0r1mnvjs.tpx\Micro Platforms\default\debuggers\VM_DBG" -I"C:\Program Files (x86)\Arduino\libraries" -I"C:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries" -I"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\0r1mnvjs.tpx\Micro Platforms\default\debuggers" -I"c:\Projects\Arduino\libraries" "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\0r1mnvjs.tpx\Micro Platforms\default\debuggers\VM_DBG\VM_DBG.cpp" -o "C:\Users\Bart.Thompson\AppData\Local\V.Micro\Arduino\Builds\ECBMSlave\yun\VM_DBG\VM_DBG.cpp.o" -DVM_DEBUG -DVM_DEBUG_ENABLE=1 -DVM_DEBUG_BANDWIDTH_THROTTLE_MS=33 -DVM_DEBUGGER_TYPE_HARDWARESERIAL=0 -DVM_DEBUGGER_TYPE_SOFTWARESERIAL=1 -DVM_DEBUGGER_TYPE_FASTSERIAL=2 -DVM_DEBUGGER_TYPE_USB=3 -DVM_DEBUGGER_TYPE_TEENSY=4 -DVM_DEBUGGER_TYPE_UART=5 -DVM_DEBUGGER_TYPE_USART=6 -DVM_DEBUGGER_TYPE_USBSERIAL=7 -DVM_DEBUGGER_TYPE_TTYUART=8 -DVM_DEBUGGER_TYPE_NET_CONSOLE=9 -DVM_DEBUGGER_TYPE_Uart=10 -DVM_DEBUGGER_TYPE_COSA=11 -DVM_DEBUGGER_TYPE_CDCSerialClass=12 -DVM_DEBUGGER_TYPE=VM_DEBUGGER_TYPE_USB -DVM_DEBUG_BREAKPAUSE
Error compiling libraries

**Comment by PaulStoffregen** [comment]
Incompatible board selected in Tools > Boards?

**Comment by barttt** [comment]
Wow I am impressed. Thats about the fastest reply ever. 
I had Teensy 3.2 selected in the pulldown (visual studio 15 /w visual micro) when the errors showed. Reselected Teensy 3.2, and built again - no Errors! Go figure. I wish there was a NetBeans IDE instead, this VS ide leaves a lot to be desired.
Thanks for the quick reply Paul, you're a gentleman and a scholar.
